### ISSUE TITLE
dht panic: send on closed channel during FindProvidersAsync

### ISSUE THREAD

**Issue by briantigerchow** [jbenet/go-ipfs#460]
at fa6e63c702dc3f4214b80c3c44bb84bd354adcbe 

bug discovered through network test: https://build.protocol-dev.com/job/network-test/151/

client log reveals:

```
11:18:36.331 DEBUG      swarm: peer Qmbtc3 sent message to peer Qmbtc2 (17358) conn.go:200
11:18:36.192 DEBUG        dht: ERROR worker for: peer Qmbtc2 no response to request query.go:251
11:18:36.332 DEBUG        dht: completing worker for: peer QmNXuB query.go:231
panic: runtime error: send on closed channel

goroutine 34606 [running]:
runtime.panic(0xa29f20, 0xe83e69)
        /usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/jbenet/go-ipfs/routing/dht.func·004(0x7fa5635ad568, 0xc20df40540, 0x7fa5635adfb0, 0xc2082321e0, 0xc2082321e0, 0x0, 0x0)
        /go/src/github.com/jbenet/go-ipfs/routing/dht/routing.go:180 +0x92a
github.com/jbenet/go-ipfs/routing/dht.(*dhtQueryRunner).queryPeer(0xc208377a80, 0x7fa5635adfb0, 0xc2082321e0)
        /go/src/github.com/jbenet/go-ipfs/routing/dht/query.go:248 +0x5b9
created by github.com/jbenet/go-ipfs/routing/dht.(*dhtQueryRunner).spawnWorkers
        /go/src/github.com/jbenet/go-ipfs/routing/dht/query.go:209 +0x283
```

**Comment by jbenet** [comment]
I doubt this is a thing-- pls reopen if found again.
