### ISSUE TITLE
old ipfs configs broken

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#552]
Since the new repo changes
```
> ipfs config Addresses
Error: Failure to decode config: json: cannot unmarshal string into Go value of type []string
> ipfs config show
Error: Failure to decode config: json: cannot unmarshal string into Go value of type []string
> ipfs init -f
Error: Failure to decode config: json: cannot unmarshal string into Go value of type []string
```
removing everything manually works.

cc @briantigerchow

**Comment by jbenet** [comment]
Also:
```
ipfs config Addresses.Swarm.0
panic: interface conversion: interface is []interface {}, not map[string]interface {}

goroutine 16 [running]:
runtime.panic(0x464a8e0, 0xc20803b380)
	/usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/panic.c:279 +0xf5
github.com/jbenet/go-ipfs/repo/common.MapGetKV(0xc208109d10, 0x7fff5fbff184, 0x11, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/repo/common/common.go:13 +0x163
github.com/jbenet/go-ipfs/repo/fsrepo.(*FSRepo).GetConfigKey(0xc208087240, 0x7fff5fbff184, 0x11, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/repo/fsrepo/fsrepo.go:183 +0x270
github.com/jbenet/go-ipfs/core/commands.getConfig(0x4e115a0, 0xc208087240, 0x7fff5fbff184, 0x11, 0x2, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/core/commands/config.go:147 +0x72
github.com/jbenet/go-ipfs/core/commands.func·014(0x4e111d8, 0xc20804ad20, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/core/commands/config.go:74 +0x33a
github.com/jbenet/go-ipfs/commands.(*Command).Call(0x4b4b000, 0x4e111d8, 0xc20804ad20, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/commands/command.go:102 +0x3bb
main.callCommand(0x4e11198, 0xc208108900, 0x4e111d8, 0xc20804ad20, 0x4b4b000, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:344 +0x7e3
main.(*cmdInvocation).Run(0xc20803a0c0, 0x4e11198, 0xc208108900, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:162 +0x2ba
main.main()
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:123 +0x475
```

**Comment by jbenet** [comment]
Oh wow, this actually broke it:
```
> ipfs config Addresses.Swarm "[\"/ip4/0.0.0.0/tcp/0\"]"
Error: Failed to set config value: Failure to decode config: json: cannot unmarshal string into Go value of type []string

> ipfs daemon
Error: Failure to decode config: json: cannot unmarshal string into Go value of type []string
```

**Comment by briantigerchow** [comment]
I don't understand why old configs would be broken. Can you post an old config that reproduces the issue so we can compare?

**Comment by jbenet** [comment]
here's my old config. just pop in a key + change the PeerID

```
{
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Gateway": "/ip4/127.0.0.1/tcp/6001",
    "Swarm": "/ip4/0.0.0.0/tcp/0"
  },
  "Bootstrap": [
    {
      "Address": "/ip4/104.131.131.82/tcp/4001",
      "PeerID": "QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ"
    },
    {
      "Address": "/ip4/104.236.176.52/tcp/4001",
      "PeerID": "QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z"
    },
    {
      "Address": "/ip4/104.236.179.241/tcp/4001",
      "PeerID": "QmSoLpPVmHKQ4XTPdz8tjDFgdeRFkpV8JgYq8JVJ69RrZm"
    },
    {
      "Address": "/ip4/162.243.248.213/tcp/4001",
      "PeerID": "QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm"
    },
    {
      "Address": "/ip4/128.199.219.111/tcp/4001",
      "PeerID": "QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu"
    }
  ],
  "Datastore": {
    "Path": "/Users/jbenet/.go-ipfs/datastore",
    "Type": "leveldb"
  },
  "Identity": {
    "PeerID": "QmeuCdBJK248A95VnD8EWRryeSuyNKHHQ3uBEgDkqZ8iTs",
    "PrivKey": "<redacted -- i'm using the same key elsewhre>"
  },
  "Logs": {
    "Filename": "/Users/jbenet/.go-ipfs/logs/events.log",
    "MaxAgeDays": 0,
    "MaxBackups": 0,
    "MaxSizeMB": 0
  },
  "Mounts": {
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Tour": {
    "Last": ""
  },
  "Version": {
    "AutoUpdate": "minor",
    "Check": "error",
    "CheckDate": "2015-01-13T09:48:31.042630482-08:00",
    "CheckPeriod": "172800000000000",
    "Current": "0.1.7"
  }
}
```

**Comment by briantigerchow** [comment]
> pop in a key

put a key where?

**Comment by jbenet** [comment]
in `Identity`

**Comment by briantigerchow** [comment]
oh. when did the swarm become a list?

**Comment by jbenet** [comment]
@briantigerchow good catch. not sure. it may also have been marshalling/unmarshalling too smartly?
