### ISSUE TITLE
panic kindof in the blockservice

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#624]
I started the ipfs daemon, added a bunch of files, then sent a SIGINT to the daemon to shut it down, it didnt shut down immediately and when i came back to the screen that the daemon was running on, it had panicked:

```
04:07:00.617  INFO     swarm2: <peer.ID QmepQC> --> <peer.ID QmNM5q> dial attempt failed: dial tcp4 58.7.118.14:17026: i/o timeout prefixlog.go:116
04:07:00.618  INFO     swarm2: <peer.ID QmepQC> --> <peer.ID QmNM5q> dial attempt failed: dial tcp4 58.7.118.14:17370: i/o timeout prefixlog.go:116
04:07:00.618  INFO     swarm2: <peer.ID QmepQC> --> <peer.ID QmNM5q> dial attempt failed: dial tcp4 58.7.118.14:17841: i/o timeout prefixlog.go:116
04:07:00.619  INFO     swarm2: <peer.ID QmepQC> --> <peer.ID QmNM5q> dial attempt failed: dial tcp4 58.7.118.14:16032: i/o timeout prefixlog.go:116
04:07:00.619  INFO     swarm2: <peer.ID QmepQC> --> <peer.ID QmNM5q> dial attempt failed: dial tcp4 58.7.118.14:17346: i/o timeout prefixlog.go:116
04:07:00.619  INFO     swarm2: <peer.ID QmepQC> --> <peer.ID QmNM5q> dial attempt failed: dial tcp4 58.7.118.14:13794: i/o timeout prefixlog.go:116
04:07:00.619  INFO     swarm2: <peer.ID QmepQC> --> <peer.ID QmNM5q> dial attempt failed: dial tcp4 58.7.118.14:17027: i/o timeout prefixlog.go:116
04:07:00.619  INFO     swarm2: <peer.ID QmepQC> --> <peer.ID QmNM5q> dial attempt failed: dial tcp4 58.7.118.14:17210: i/o timeout prefixlog.go:116
04:07:00.620 DEBUG     swarm2: swarm <peer.ID QmepQC> dialing <peer.ID QmNM5q> dial end <nil> prefixlog.go:107
04:07:00.620 ERROR        dht: dht(<peer.ID QmepQC>) Provide(QmUhXZ4YbvnRxB2EDBLsYGEpswC545eyUobVFJNsNHq7QT) <peer.ID QmepQC> --> <peer.ID QmNM5q> dial attempt failed: dial tcp4 58.7.118.14:17210: i/o timeout prefixlog.go:110
panic: Process cannot add children after being closed

goroutine 66 [running]:
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).AddChild(0x10b28d40, 0xb6d40bb0, 0x12374180)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:68 +0xbc
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go(0x10b28d40, 0x10d36e00, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:79 +0x1e8
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/ratelimit.(*RateLimiter).LimitedGo(0x114b80c0, 0x10d36e00)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/ratelimit/ratelimit.go:48 +0xb4
github.com/jbenet/go-ipfs/blockservice/worker.funcÂ·003(0xb6d40bb0, 0x10b9c240)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/blockservice/worker/worker.go:136 +0x284
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.funcÂ·005()
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:84 +0x8c
created by github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:87 +0x44c

goroutine 1 [chan receive]:
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-ctxgroup.(*contextGroup).Close(0x10ba6480, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-ctxgroup/ctxgroup.go:187 +0x58
main.(*cmdInvocation).close(0x10b390a0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:206 +0x118
main.main()
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:135 +0x5dc

goroutine 6 [syscall]:
os/signal.loop()
	/home/whyrusleeping/go/src/os/signal/signal_unix.go:21 +0x1c
created by os/signal.initÂ·1
	/home/whyrusleeping/go/src/os/signal/signal_unix.go:27 +0x38

goroutine 1607 [semacquire]:
sync.runtime_Semacquire(0x10ba64ac)
	/home/whyrusleeping/go/src/runtime/sema.go:43 +0x2c
sync.(*Mutex).Lock(0x10ba64a8)
	/home/whyrusleeping/go/src/sync/mutex.go:66 +0xf8
sync.(*Once).Do(0x10ba64a8, 0x1164f818)
	/home/whyrusleeping/go/src/sync/once.go:40 +0x7c
created by github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-ctxgroup.(*contextGroup).internalClose
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-ctxgroup/ctxgroup.go:200 +0xa0

goroutine 10 [chan receive]:
main.funcÂ·011()
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:496 +0x50
created by main.(*cmdInvocation).setupInterruptHandler
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:518 +0x130

goroutine 49 [select]:
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream.(*Swarm).connGarbageCollect(0x114b26c0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream/swarm.go:351 +0x1bc
created by github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream.NewSwarm
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream/swarm.go:56 +0x26c

goroutine 21 [chan send]:
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-datastore/namespace.funcÂ·003()
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-datastore/namespace/namespace.go:78 +0x2ec
created by github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-datastore/namespace.(*datastore).Query
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-datastore/namespace/namespace.go:80 +0x20c

goroutine 1599 [chan receive]:
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-ctxgroup.(*contextGroup).Close(0x10ba6480, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-ctxgroup/ctxgroup.go:187 +0x58
main.funcÂ·010()
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:509 +0x50
created by main.funcÂ·011
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:511 +0x330

goroutine 1628 [chan receive]:
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).doClose(0x10b9c240)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:128 +0x184
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Close(0x10b9c240, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:104 +0x100
created by github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).doClose
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:124 +0xc8

goroutine 1600 [chan receive]:
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).doClose(0x10b3bfc0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:128 +0x184
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Close(0x10b3bfc0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:104 +0x100
github.com/jbenet/go-ipfs/blockservice/worker.(*Worker).Close(0x10b9a660, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/blockservice/worker/worker.go:74 +0x10c
github.com/jbenet/go-ipfs/blockservice.(*BlockService).Close(0x10b9a680, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/blockservice/blockservice.go:147 +0xe8
github.com/jbenet/go-ipfs/core.(*IpfsNode).teardown(0x1143c240, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/core/core.go:285 +0x624
github.com/jbenet/go-ipfs/core.*IpfsNode.(github.com/jbenet/go-ipfs/core.teardown)Â·fm(0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/core/core.go:116 +0x34
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-ctxgroup.(*contextGroup).closeLogic(0x10ba6480)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-ctxgroup/ctxgroup.go:209 +0x38
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-ctxgroup.*contextGroup.(github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-ctxgroup.closeLogic)Â·fm()
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-ctxgroup/ctxgroup.go:200 +0x24
sync.(*Once).Do(0x10ba64a8, 0x118c17d0)
	/home/whyrusleeping/go/src/sync/once.go:44 +0x128
created by github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-ctxgroup.(*contextGroup).internalClose
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-ctxgroup/ctxgroup.go:200 +0xa0

goroutine 1564 [semacquire]:
sync.runtime_Semacquire(0x10ba64ac)
	/home/whyrusleeping/go/src/runtime/sema.go:43 +0x2c
sync.(*Mutex).Lock(0x10ba64a8)
	/home/whyrusleeping/go/src/sync/mutex.go:66 +0xf8
sync.(*Once).Do(0x10ba64a8, 0x1149d6c8)
	/home/whyrusleeping/go/src/sync/once.go:40 +0x7c
created by github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-ctxgroup.(*contextGroup).internalClose
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-ctxgroup/ctxgroup.go:200 +0xa0

goroutine 1219 [runnable]:
sync.(*Mutex).Unlock(0x11988840)
	/home/whyrusleeping/go/src/sync/mutex.go:82
sync.(*WaitGroup).Add(0x11988840, 0xffffffff)
	/home/whyrusleeping/go/src/sync/waitgroup.go:80 +0x188
sync.(*WaitGroup).Done(0x11988840)
	/home/whyrusleeping/go/src/sync/waitgroup.go:85 +0x2c
github.com/jbenet/go-ipfs/routing/dht.funcÂ·008(0x12e927b0, 0x22)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/routing/dht/routing.go:154 +0x2d4
created by github.com/jbenet/go-ipfs/routing/dht.(*IpfsDHT).Provide
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/routing/dht/routing.go:154 +0x66c
```

**Comment by jbenet** [comment]
I changed the `goprocess` child code (fixed some problems in the last few days). It's now on master. If we get another panic like this it will either show us imporper relationship mgmt on our part, or I may remove that panic and update the semantics to: adding a child to a closed process succeeds but immediately signals close.

**Comment by whyrusleeping** [comment]
Okay, ill leave this open for a few more days then, if we dont see it again ill assume its been fixed.
