### ISSUE TITLE
panic in ipfs dht findprovs

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#757]
Panic in ipfs dht findprovs

```
 % ipfs dht findprovs QmSKiuWBP1Y4Xmpxh4uySrEvnGYPFwj3Qy3uKNi9fQeVhe
QmNaFWP1vMk57i62PugNTPY3RBDYP66B6Ek3xnHCQYD8ui
QmSoLpPVmHKQ4XTPdz8tjDFgdeRFkpV8JgYq8JVJ69RrZm
QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu
panic: interface conversion: interface is nil, not []interface {} [recovered]
	panic: interface conversion: interface is nil, not []interface {} [recovered]
	panic: interface conversion: interface is nil, not []interface {}

goroutine 33 [running]:
encoding/json.func·001()
	/usr/local/go/src/encoding/json/decode.go:135 +0x8b
encoding/json.func·001()
	/usr/local/go/src/encoding/json/decode.go:135 +0x8b
github.com/jbenet/go-ipfs/p2p/peer.(*PeerInfo).UnmarshalJSON(0xc2081ac000, 0xc208152060, 0x59, 0x1da0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/p2p/peer/peer.go:157 +0x263
encoding/json.(*decodeState).object(0xc20817cb40, 0x70d8a0, 0xc2081a1760, 0xd6)
	/usr/local/go/src/encoding/json/decode.go:481 +0x133
encoding/json.(*decodeState).value(0xc20817cb40, 0x70d8a0, 0xc2081a1760, 0xd6)
	/usr/local/go/src/encoding/json/decode.go:288 +0x3ce
encoding/json.(*decodeState).array(0xc20817cb40, 0x59d440, 0xc2081975d8, 0xd7)
	/usr/local/go/src/encoding/json/decode.go:439 +0xa9b
encoding/json.(*decodeState).value(0xc20817cb40, 0x59d440, 0xc2081975d8, 0xd7)
	/usr/local/go/src/encoding/json/decode.go:285 +0x3ee
encoding/json.(*decodeState).object(0xc20817cb40, 0x73f2e0, 0xc2081975c0, 0xd9)
	/usr/local/go/src/encoding/json/decode.go:605 +0x1199
encoding/json.(*decodeState).value(0xc20817cb40, 0x599d20, 0xc2081975c0, 0x16)
	/usr/local/go/src/encoding/json/decode.go:288 +0x3ce
encoding/json.(*decodeState).unmarshal(0xc20817cb40, 0x599d20, 0xc2081975c0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:149 +0x1e7
encoding/json.Unmarshal(0xc208152000, 0x12b, 0x1e00, 0x599d20, 0xc2081975c0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:78 +0x145
github.com/jbenet/go-ipfs/notifications.(*QueryEvent).UnmarshalJSON(0xc2081a8d40, 0xc208152000, 0x12b, 0x1e00, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/notifications/query.go:66 +0x9f
encoding/json.(*decodeState).object(0xc20816e028, 0x70d6e0, 0xc2081a8d40, 0x16)
	/usr/local/go/src/encoding/json/decode.go:481 +0x133
encoding/json.(*decodeState).value(0xc20816e028, 0x70d6e0, 0xc2081a8d40, 0x16)
	/usr/local/go/src/encoding/json/decode.go:288 +0x3ce
encoding/json.(*decodeState).unmarshal(0xc20816e028, 0x70d6e0, 0xc2081a8d40, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:149 +0x1e7
encoding/json.(*Decoder).Decode(0xc20816e000, 0x70d6e0, 0xc2081a8d40, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:53 +0x18f
github.com/jbenet/go-ipfs/commands/http.func·001()
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/commands/http/client.go:170 +0x225
created by github.com/jbenet/go-ipfs/commands/http.getResponse
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/commands/http/client.go:184 +0x5be

goroutine 1 [chan receive]:
github.com/jbenet/go-ipfs/commands.(*ChannelMarshaler).Read(0xc20815e080, 0xc208166000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/commands/channelmarshaler.go:14 +0x8a
io.Copy(0xdce210, 0xc20804e008, 0xdd0870, 0xc20815e080, 0x8d, 0x0, 0x0)
	/usr/local/go/src/io/io.go:362 +0x1f6
main.main()
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:147 +0x6b1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 9 [chan receive]:
main.func·014()
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:479 +0x63
created by main.(*cmdInvocation).setupInterruptHandler
	/Users/jbenet/go/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:503 +0x121

goroutine 17 [select]:
net/http.(*persistConn).readLoop(0xc208074420)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 18 [select]:
net/http.(*persistConn).writeLoop(0xc208074420)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

```

**Comment by whyrusleeping** [comment]
finally figured this one out, it happens when we receive a peer that has no addresses (for some reason). My terribad marshaler apparently doesnt know how to handle it...
