### ISSUE TITLE
goprocess panic

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#771]
Wasnt really paying attention to my daemon, and came back to this:

```
Initializing daemon...
API server listening on /ip4/127.0.0.1/tcp/5001
panic: Process cannot wait after being closed

goroutine 109944 [running]:
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).WaitFor(0x118f4f80, 0xb6d98c38, 0x118f5140)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:46 +0x114
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go(0x110f6d40, 0x12cbfd00, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:94 +0x38c
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/ratelimit.(*RateLimiter).LimitedGo(0x12cbb0c0, 0x12cbfd00)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/ratelimit/ratelimit.go:48 +0xb4
github.com/jbenet/go-ipfs/p2p/net/swarm.funcÂ·006(0xb6d98c38, 0x110f6e80)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/p2p/net/swarm/swarm_dial.go:402 +0x210
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.funcÂ·005()
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:96 +0x8c
created by github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:99 +0x44c

goroutine 1 [select, 20 minutes]:
github.com/jbenet/go-ipfs/core/corehttp.listenAndServe(0x10c42a20, 0xb6d993d8, 0x10ca78b0, 0x11d92180, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/core/corehttp/corehttp.go:59 +0x580
github.com/jbenet/go-ipfs/core/corehttp.ListenAndServe(0x10c42a20, 0x11d92140, 0x17, 0x11946d18, 0x3, 0x3, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/core/corehttp/corehttp.go:38 +0x1bc
main.daemonFunc(0xb6d99698, 0x10c3a2a0, 0xb6d99770, 0x10c36a00)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/cmd/ipfs/daemon.go:135 +0x121c
github.com/jbenet/go-ipfs/commands.(*Command).Call(0x9be480, 0xb6d99698, 0x10c3a2a0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/commands/command.go:98 +0x424
main.callCommand(0xb6d99670, 0x10c905a0, 0xb6d99698, 0x10c3a2a0, 0x9be480, 0x9b9548, 0x0, 0x0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:325 +0x820
main.(*cmdInvocation).Run(0x10c905c0, 0xb6d99670, 0x10c905a0, 0x0, 0x0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:164 +0x1dc
main.main()
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/cmd/ipfs/main.go:135 +0x578
```

**Comment by jbenet** [comment]
Was this on master? I changed this part recently and want to make sure which one it is.

**Comment by whyrusleeping** [comment]
I think it was on master.

**Comment by whyrusleeping** [comment]
I really need to start putting commit hashes with panics i file

**Comment by whyrusleeping** [comment]
Found this on my pi (which had been running great up til now!)
```
panic: Process cannot wait after being closed

goroutine 15162646 [running]:
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).WaitFor(0x16089b00, 0xb6d45158, 0x16089c00)
        /home/pi/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:46 +0x114
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go(0x121edfc0, 0x1427ce40, 0x0, 0x0)
        /home/pi/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:94 +0x384
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/ratelimit.(*RateLimiter).LimitedGo(0x11c29390, 0x1427ce40)
        /home/pi/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/ratelimit/ratelimit.go:48 +0xa8
github.com/jbenet/go-ipfs/p2p/net/swarm.funcÂ·006(0xb6d45158, 0x125fb640)
         /home/pi/gopkg/src/github.com/jbenet/go-ipfs/p2p/net/swarm/swarm_dial.go:402 +0x210
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.funcÂ·005()
         /home/pi/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:96 +0x8c
created by github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
        /home/pi/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:99 +0x448
```

**Comment by cryptix** [comment]
I had two of those, as well.

Here are the logs if you need them:

[QmdcQ89TQw43Z3AtGin8mhA8UkAwBSFXUpYNGn7M9W1JJU](http://gateway.ipfs.io/ipfs/QmdcQ89TQw43Z3AtGin8mhA8UkAwBSFXUpYNGn7M9W1JJU)
[QmSDYyq266Jx7jtV7Tz4D4dWsq82mCQ7SAbm8Km4MPfqp5](http://gateway.ipfs.io/ipfs/QmSDYyq266Jx7jtV7Tz4D4dWsq82mCQ7SAbm8Km4MPfqp5)

**Comment by xorgy** [comment]
Sometimes when this happens, it leaves the store locked, which prevents you from running the daemon again, even if you remove the LOCK file, it puts it back wheny ou run `ipfs daemon`

**Comment by xorgy** [comment]
Also, I'm testing the same things on another machine, running OS X 10.10 and Go 1.3.3 (which actually compiles and runs ipfs just fine), and on that machine I'm not experiencing this issue, at least not yet.

Though I don't use that machine as much, so I might just not have done enough to trigger it.

**Comment by whyrusleeping** [comment]
@xorgy thanks for the feedback! I just hit this one again myself, so that bumps it up on my priority queue a bit.

**Comment by xorgy** [comment]
More fail for your appraisal.

http://gateway.ipfs.io/ipfs/QmfSFQS9L7jGrtkknGa6959ZqK8MqAkKjZ8AuZ9MhwV2M3
