### ISSUE TITLE
panic on killing daemon

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#781]
Got another one!
```
panic: Process cannot add children after being closed

goroutine 17969 [running]:
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).AddChild(0x12292b40, 0xb6d01838, 0x12292cc0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:80 +0x114
github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go(0x12292b40, 0x117358a0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:91 +0x1e8
github.com/jbenet/go-ipfs/p2p/net/swarm.funcÂ·007()
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/p2p/net/swarm/swarm_dial.go:404 +0x1c4
created by github.com/jbenet/go-ipfs/p2p/net/swarm.(*Swarm).dialAddrs
	/home/whyrusleeping/gopkg/src/github.com/jbenet/go-ipfs/p2p/net/swarm/swarm_dial.go:405 +0x698
```

**Comment by whyrusleeping** [comment]
@jbenet this is similar to #771
